### PR TITLE
Fixed init script for debian based instance.

### PR DESCRIPTION
**Pull request by Sliim**

### CODE REVIEW

**Comment by PierreRambaud** [comment]
:+1:

**Comment by Sliim** [comment]
ping @bflad

**Comment by bflad** [comment]
Oi vei, I definitely was out of commission way too long for such a simple fix. I'm really sorry about that. For those still following along, I'd suggest switching over to the much better and supported afklm fork, which is now officially the `jira` cookbook: https://supermarket.chef.io/cookbooks/jira - see #22 for discussion and details.

**Comment by Sliim** [comment]
Ok no problem! Thanks for your reply!

**Pull request closed without merging**
