### PR TITLE
Get rid of derived attributes

### PR DESCRIPTION
**Pull request by legal90**
Includes PRs from the similar cookbook `confluense`:
- Set version dependent attributes in the separated recipe [https://github.com/bflad/chef-confluence/pull/30]
- Stop storing state in attributes [https://github.com/bflad/chef-confluence/issues/62]

Attributes, which default value depends on the value of another attribute, should be defined in the recipe or library, but not in attribute file.
Otherwise, it is very hard to override such attributes or wrap this cookbook in another one.

Example:
Attributes `checksum` and `url` depend on the `version` value. If you want to override `version`, then you should override `checksum` and `url` as well, because their default values are calculated on the step of attribute file parsing, e.q. _before_ `version` value will be explored according to the priority.

That's why it's better to move this logic to the library. In this case the value of `version` attribute will be calculated correctly. This is so called "Derived Attributes" issue, and you can find more detaled explanation of this problem here: https://coderanger.net/derived-attributes/

/cc: @bflad

### CODE REVIEW

**Comment by legal90** [comment]
I also would like to adopt this cookbook and maintain it, as I already do with your Confluence cookbook. I'm gonna test and merge opened PR and send the new one. 
I'm planning to add a support for new JIRA 7 and deprecate `war` installation type support, because it is not supported by Atlassian anymore.

@bflad, don't you mind to transfer an ownership of this cookbook?  Thanks.

**Comment by patcon** [comment]
fwiw I unfortunately wasn't seeing any progress or responses in the cookbook's queue, and so have moved my efforts to @afklm's fork:
https://github.com/afklm/chef_jira/pulls

**Comment by legal90** [comment]
@patcon Yes I see it is inactive, that's why I ask @bflad about ownership transfer ;-)
Actually, KLM's fork looks good, but I don't like how they have renamed it :-). And I also would like to get rid of all this complex logic around the WAR installation type. I think it will allow to make the cookbook much lighter and clearer.

Well, seeing your activity there, may be I should also move my effort to KLM's fork...

**Comment by patcon** [comment]
Didn't have any luck with that myself, but hopefully you fare better! https://github.com/bflad/chef-jira/issues/20

imho, it would make sense to ask for full ownership (and transfer to your github namespace?), rather than just collab status. You or someone else should really be first-class owners with the ability to do all admin functions, given that @bflad sometimes goes through long periods of busyness :) For instance, you had made serveral requests to give me admin access to tag new releases on github, and that went unaddressed as well.

**Comment by mvdkleijn** [comment]
Hey @legal90 

I understand you don't like the rename. I didn't really want to but for it to be published to the supermarket, we had to. There's already a semi active cookbook on the supermarket with the name jira but it is unusable for us for various reasons.

**Comment by patcon** [comment]
Actually, @juliandunn, if someone were to convert Opscode's [`jira` cookbook](https://github.com/juliandunn/jira) into a wrapper around @mvdkleijn's `chef_jira`, then would you be willing to provide the canonical `jira` namespace on supermarket? :)

**Comment by juliandunn** [comment]
I'm happy to give up the `jira` namespace on the Supermarket -- we should all work together as a community to decide on *one* Jira cookbook and collaborate on it. I personally have no stake in this game because I no longer need to manage/install Jira.

**Comment by ramonskie** [comment]
@juliandunn can you assign the namespace to https://supermarket.chef.io/users/mvdkleijn

**Comment by juliandunn** [comment]
Done!

**Comment by legal90** [comment]
@juliandunn Cool, thanks! :clap: 

So, I close this PR. Let's concentrate the effort to the new fork!

**Comment by mvdkleijn** [comment]
@juliandunn I realize this is a little off topic, but now that we have your attention, would you be willing to help transfer crowd to my user account too? (seeing as its claimed but unused by one of your coworkers)

@thommay requested me to sent an email about this to him and @btm and indicated that he thought transferring it would not be a problem. I sent the email on 18th of August but unfortunately never heard back even after another ping...

**Comment by juliandunn** [comment]
Yes, I will speak with Thom.

**Comment by juliandunn** [comment]
@mvdkleijn btm was sitting next to me just now so we did the needful for you!

**Comment by patcon** [comment]
Funny how when you mostly interact with people over the internet, hearing about them side-by-side is some kinda weird cheap thrill :) And oddly, I'm now imagining you both drinking wine like this: wine arms

**Comment by juliandunn** [comment]
@patcon ROFL.

**Comment by mvdkleijn** [comment]
@juliandunn Thanks for the assist. :smile:

**Comment by bflad** [comment]
Thanks @legal90 @juliandunn @patcon for doing the right thing here. I'll put a deprecation notice on the top of the README and point to the better fork.

**Comment by patcon** [comment]
Thanks very much for everything @bflad :)

**Pull request closed without merging**
